version: "3"
services:
    dockstar-db:
        image: mysql:5.6
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - DS_USERNAME
            - DS_PASSWORD
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./darkstar/sql:/tmp/darkstar/sql/:ro
            - ./scripts/mysql:/docker-entrypoint-initdb.d/:ro
            
    dockstar-server:
        depends_on:
            - dockstar-db
        image: dockstar-server
        build:
            context: .
            dockerfile: dockerfiles/dockstar-server.dockerfile
        environment:
            - ZONE_IP
            - DS_GMS_LIST
            - DS_USERNAME
            - DS_PASSWORD
            - DS_SERVERNAME
        ports:
            - "54001:54001"
            - "54002:54002"
            - "54231:54231"
            - "53445:53445"
            - "54230:54230/udp"
            - "54230:54230/tcp"
        volumes:
            - ./scripts/start-darkstar.sh:/home/dockstar/darkstar/start-darkstar.sh
            - ./conf/login_darkstar.skel:/home/dockstar/darkstar/conf/login_darkstar.skel
            - ./conf/map_darkstar.skel:/home/dockstar/darkstar/conf/map_darkstar.skel
            - ./conf/search_server.skel:/home/dockstar/darkstar/conf/search_server.skel
            - ./conf/server_message.skel:/home/dockstar/darkstar/conf/server_message.skel
            - ./conf/settings.lua:/home/dockstar/darkstar/scripts/settings.lua